name: Node.js CI

on:
  pull_request:
    branches: ["main"]

env:
  NEXT_PUBLIC_MOCK_NEXT_AUTH: false
  DATABASE_URL: "postgres://jonathan:pass@localhost:5432/capacitacao"
  NEXTAUTH_SECRET: "dummysecret"
  NEXTAUTH_URL: "http://localhost:3000"
  GOOGLE_CLIENT_ID: 123
  GOOGLE_CLIENT_SECRET: 123

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - run: SKIP_ENV_VALIDATION=1 npm run type-check
      - run: SKIP_ENV_VALIDATION=1 npm run lint
      - run: SKIP_ENV_VALIDATION=1 npm run build --if-present
  format:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - run: npm ci
      - run: SKIP_ENV_VALIDATION=1 npm run format
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: "Tubias Bot Formatter"
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
